# file: roles/common/handlers/main.yml
- name: Restart server
  tags: selinux
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  tags: selinux
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30 timeout=300
  become: false