# file: roles/webtier/tasks/main.yml
- include: remi.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
- include: ondrej.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'  
- include: php.yml
- include: php-fpm.yml
- include: composer.yml
- include: nginx.yml
- include: dotenv.yml
- include: cron.yml
- include: letsencrypt.yml
  when: enable_ssl|default(false)|bool == true
- include: firewalld.yml
- include: redis.yml
- include: selinux.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

