# file: roles/common/tasks/swap.yml
- name: Check if additional swap is needed
  tags: swap
  when: ansible_memtotal_mb < 1024
  set_fact:
    needs_extra_swap: true

- name: Check if swap exists
  tags: swap
  when: needs_extra_swap is defined and needs_extra_swap == true
  stat:
    path: /swapfile
  register: swap_file_check

- name: Generate swapfile
  tags: swap
  command: dd if=/dev/zero of=/swapfile count=1024 bs=1MiB
  register: generate_swapfile
  when: needs_extra_swap is defined and needs_extra_swap == true and swap_file_check.stat.exists == false

- name: Set permissions on swapfile
  tags: swap
  file: path=/swapfile mode=0600
  when: needs_extra_swap is defined and needs_extra_swap == true and swap_file_check.stat.exists == true

- name: Create swapfile
  tags: swap
  command: mkswap /swapfile
  when: needs_extra_swap is defined and needs_extra_swap == true and swap_file_check.stat.exists == false

- name: Enable swapfile
  tags: swap
  command: swapon /swapfile
  when: needs_extra_swap is defined and needs_extra_swap == true and swap_file_check.stat.exists == false

- name: Add swapfile to /etc/fstab
  tags: swap
  lineinfile: dest=/etc/fstab line="/swapfile   swap    swap    sw  0   0" state=present
  when: needs_extra_swap is defined and needs_extra_swap == true

- name: Set swapfile permissions
  tags: swap
  file: path=/swapfile mode=0600
  when: needs_extra_swap is defined and needs_extra_swap == true

- name: Configure vm.swappiness
  tags: swap
  sysctl:
    name: vm.swappiness
    value: "1"
  when: needs_extra_swap is defined and needs_extra_swap == true

- name: Configure vm.vfs_cache_pressure
  tags: swap
  sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
  when: needs_extra_swap is defined and needs_extra_swap == true
